# Generated by Django 4.2.17 on 2024-12-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='pictures/', verbose_name='Фото',null=False)),
                ('audio', models.FileField(upload_to='audio/', verbose_name='Аудио',null=False)),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка')),
            ],
        ),
    ]
