# Generated by Django 4.2.17 on 2024-12-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
    ]
