# Generated by Django 4.2.17 on 2024-12-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_cards_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='photo',
            field=models.ImageField(default='default_image.jpg', upload_to='pictures/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='audio',
            field=models.FileField(verbose_name="Аудио", upload_to='audio/'),
        ),
    ]
