# Generated by Django 4.2.17 on 2024-12-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cards_photo_alter_cards_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='audio',
            field=models.FileField(upload_to='audio/', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='photo',
            field=models.ImageField(upload_to='pictures', verbose_name='Фото'),
        ),
    ]
